# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a32a7b761fe85cdb1c126368a2b21ee961358a8b4d16214fdc97769fb0da466368847fe495951f6351f90752f1ae3016d5ef716a12ce35732572199a9f8eb91

test:
  secret_key_base: 19fc57b993e155ea4468202ed9325812dcdb64fb8f01d0fadec70f03a23393568fa9de5292d9d4807c2cc334e501a2f7340d340ff86ed82434c4e5ad7c77816e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
